version: '3.8'

services:
  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_API_URL=http://15.252.129.37:8200/api/v1
    container_name: strive_wheels_admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
