# 1. Install dependencies
FROM node:22-alpine AS deps
WORKDIR /app

COPY package*.json package-lock.json* ./
RUN npm install

# 2. Build stage
FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_API_URL=http://15.252.129.37:8200/api/v1
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN rm -rf .next
RUN npm run build

# 3. Runtime
FROM node:22-alpine AS runner
WORKDIR /app
ENV PORT=3000

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]